controller:
  replicas: 1
  manager:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc:8200"
  