apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-repo-secret
  namespace: argocd

spec:
  type: kv-v2
  mount: secret
  path: argocd/repo
  vaultAuthRef: default
  destination:
    name: argocd-repo-secret
    create: true
    labels:
      argocd.argoproj.io/secret-type: repository
