name: Setup Registry
description: Setup Registry

inputs:
  env: 
    required: false
    default: dev
    description: Environment to setup
  service_name:
    required: true
    description: service app
  registry_username:
    required: true
    description: registry username
  registry_password:
    required: true
    description: registry password


runs:
  using: composite
  steps:
    - name: Login Registry
      shell: bash
      run: |
        echo "${{ inputs.registry_password }}" | docker login \
          -u ${{ inputs.registry_username }} \
          --password-stdin
        
    - name: Build Image & Push
      shell: bash
      run: |
        IMAGE="${{ inputs.registry_username }}/${{ inputs.service_name }}"
        TAG="${{ github.sha }}"
        
        echo "Building image $IMAGE:$TAG"
        
        docker build \
        -f "cicd/services/${{ inputs.service_name }}/Dockerfile" \
        -t "$IMAGE:$TAG" \
        -t "$IMAGE:latest" \
        .
        
        docker push "$IMAGE:$TAG"
        docker push "$IMAGE:latest"
