name: Setup
description: Setup

inputs:
  env: 
    required: true
    default: dev
    description: Environment to setup

runs:
  using: composite
  steps:
    - name: Login Registry
      shell: bash
      run: |
        echo "${{ secrets.password }}" | docker login ${{ secrets.registry }} -u ${{ secrets.username }} --password-stdin
