name: builder

on:
  workflow_call:
    inputs:
      lang:
        type: string
        required: true
      version:
        type: string
        required: true

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v6
      - uses: BevisDev/cicd/actions/setup-env@main
        with:
          env: ${{ inputs.env }}
      - run: go version && go build ./..
