name: builder

on:
  workflow_call:
    inputs:
      env:
        description: "Environment"
        default: "dev"
        type: string
        required: true
      lang:
        description: "Language to build"
        type: string
        required: true
      version:
        description: "version of language"
        type: string
        required: true
      working_dir:
        description: "working directory"
        type: string
        required: false
        default: "app"
      app_name:
        description: "name of application"
        type: string
        required: false
        default: "app"
      main_dir:
        description: "main directory"
        type: string
        required: false
        default: "cmd/server"

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v6

      - name: Checkout cicd
        uses: actions/checkout@v6
        with:
          repository: BevisOrg/cicd
          path: cicd

      - name: Setup
        uses: ./cicd/actions/setup

      - if: ${{ inputs.lang == 'node' }}
        uses: ./cicd/actions/build-node
        with:
          version: ${{ inputs.version }}

      - if: ${{ inputs.lang == 'go' }}
        uses: ./cicd/actions/build-go
        with:
          version: ${{ inputs.version }}
          working_dir: ${{ inputs.working_dir }}
          app_name: ${{ inputs.app_name }}
          main_dir: ${{ inputs.main_dir }}
