name: Test Runner

on:
  workflow_call:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Print hello
        run: echo "Runner is working 🚀"

      - name: Call action
        uses: ./builds/action.yml
