name: Test Runner

on:
  workflow_call:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Print hello
        run: echo "Runner is working 🚀"

      - name: Debug before checkout
        run: ls -R

      - uses: actions/checkout@v6

      - name: Debug file structure
        run: ls -R

      - name: Call action
        uses: ./builds
